version: "3.2"

services:
  # For SSH_KEY 
  # Gitolite
  gitolite:
    image: jgiannuzzi/gitolite
    container_name: gitolite-container
    environment:
      - SSH_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDNBxSsdYo6pedTMigw49sjMYK2KQfE0gHbqtfwI82dxY4XhCzLT55HrP3tI77OhKptgWHfkeosOZ5KNP87j6DMZDTWKB7+cGj3NiL5F/p9SqSq0mowinxbs2tnM4M9FJ4zmMhIecfqcvBwb9bi0Q71WmXjx3enzuCY7usM6yJyzn1CLifo55hkHBHHUT3o8NzxEXy6etuq9LI7955f7cwH0yflYmeGVOU53iiyVzY3+MS2NOgW8eUxBvysCyI7OsPApDZKGBtsvrCNTBbwflbuTjcIM1MHYV612YsRynGx6cqpLjOtAEcmSuShJKjzI/XT/1J+9qBNEaogaCbQNDY+8uoF5v6WlZbi+WBYvbS+Dk6RC47ddvw94tPWgVnkxb3pr3dBlZMiZSAXWPV2XuROj+jDnjnd1GnIq/U2Ev9zlwSv35ZXraq+WBfDQf+BWiuXaEuX6+vUMy1Knkf8VfsCXEvdaMJjVMXm0zd3wCogpAgR4r0bMyLm+JdXmVEXVnG2KAhFDl+BFaFxnuX79rXptRAFzvN0ftPW7rG3Vibdug2X+0DIA9TDR/d5ZEjJ/ORVAGCJxM5rymIFPoaEgPuTt31U7LpEkmd7B0cVqFZ9yZ7wsr3CsSWRBqmhroRdf5z98VvOZcLrDkITgbQcSwxTJtmcVYpJOQh79pXwT9M4Rw== gitolite-admin@sandbox
    ports:
      - "2222:22"
    volumes:
      - /gitolite/uks/gitolite-data:/var/lib/git

  # Postgres as a main storage
  db:
    restart: always
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_DB=uks
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    networks:
      - uks

  # redis as a cache store
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - uks

  api:
    image: ${REGISTRY:-uks}/api:${TAG:-latest}
    container_name: api
    build:
      context: ./backend/uks
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/uks
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_PROFILES_ACTIVE=dev
      - TOKEN_SECRET=2aafbe15fde010e3a6de59e99c0adfd13bd40b60e3e5fdf351b263c3c7f72b35
    ports:
      - "8881:8881"
    volumes:
      - ./backend/uks/src/main/resources/data-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - uks

  front:
    image: ${REGISTRY:-uks}/webapp:${TAG:-latest}
    container_name: front
    build:
      context: ./frontend/uks
    networks:
      - uks

  # Nginx as a reverse proxy (gateway)
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - front
    networks:
      - uks

networks:
  uks:
    driver: bridge
