name: "Build and push image"
description: "Builds and pushes an image to a registry"

inputs:
  service:
    description: "Service to build"
    required: true
  image_name:
    description: "Name of image"
    required: true
  image_tag:
    description: "Image tag"
    required: true
  registry_username:
    description: "Registry username"
    required: true
  registry_password:
    description: "Registry password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Enable experimental features for the Docker daemon and CLI
      shell: bash
      run: |
        echo $'{\n  "experimental": true\n}' | sudo tee /etc/docker/daemon.json
        mkdir -p ~/.docker
        echo $'{\n  "experimental": "enabled"\n}' | sudo tee ~/.docker/config.json
        sudo service docker restart

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Compose build ${{ inputs.service }}
      shell: bash
      run: sudo -E docker-compose build ${{ inputs.service }}
      working-directory: .
      env:
        TAG: ${{ inputs.image_tag }}

    - name: Compose push ${{ inputs.service }}:${{ inputs.image_tag}}
      shell: bash
      run: sudo -E docker-compose push ${{ inputs.service }}:${{ inputs.image_tag}}
      working-directory: .
