version: '3.2'

services:

# Postres as a main storage
  db:
    restart: always
    image: postgres
    container_name: db
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    env_file:
      - db.env


  web:
    image: 'uks_web:latest'
    build: 
      context: ./uks
    container_name: web
    depends_on:
      - db
    # links:
    #   - db:db
      #- redis
    env_file:
      - app.env     
    ports:
      - "8881:8881"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # For SSH_KEY 
  # Gitolite
  # gitolite:
  #   image: jgiannuzzi/gitolite
  #   container_name: gitolite-container
  #   environment:
  #     - SSH_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDNBxSsdYo6pedTMigw49sjMYK2KQfE0gHbqtfwI82dxY4XhCzLT55HrP3tI77OhKptgWHfkeosOZ5KNP87j6DMZDTWKB7+cGj3NiL5F/p9SqSq0mowinxbs2tnM4M9FJ4zmMhIecfqcvBwb9bi0Q71WmXjx3enzuCY7usM6yJyzn1CLifo55hkHBHHUT3o8NzxEXy6etuq9LI7955f7cwH0yflYmeGVOU53iiyVzY3+MS2NOgW8eUxBvysCyI7OsPApDZKGBtsvrCNTBbwflbuTjcIM1MHYV612YsRynGx6cqpLjOtAEcmSuShJKjzI/XT/1J+9qBNEaogaCbQNDY+8uoF5v6WlZbi+WBYvbS+Dk6RC47ddvw94tPWgVnkxb3pr3dBlZMiZSAXWPV2XuROj+jDnjnd1GnIq/U2Ev9zlwSv35ZXraq+WBfDQf+BWiuXaEuX6+vUMy1Knkf8VfsCXEvdaMJjVMXm0zd3wCogpAgR4r0bMyLm+JdXmVEXVnG2KAhFDl+BFaFxnuX79rXptRAFzvN0ftPW7rG3Vibdug2X+0DIA9TDR/d5ZEjJ/ORVAGCJxM5rymIFPoaEgPuTt31U7LpEkmd7B0cVqFZ9yZ7wsr3CsSWRBqmhroRdf5z98VvOZcLrDkITgbQcSwxTJtmcVYpJOQh79pXwT9M4Rw== gitolite-admin@sandbox
  #   ports:
  #     - "2222:22"
  #   volumes:
  #     - /gitolite/uks/gitolite-data:/var/lib/git

  # Nginx as a web server and reverse proxy
  nginx:
    image: nginx
    container_name: uks_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/code/app/static #must be same as web!
    depends_on:
      - web

  # redis as a cache store
  redis:
    image: redis
    container_name: uks_redis
    expose:
      - '6379'
