name: API Push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/uks/**

env:
  SERVICE: api
  REGISTRY_HOST: docker.io

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Test
        run: |
          cd backend/uks && mvn clean test

  build_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: ./.github/workflows/composite/build-push
        with:
          service: ${{ env.SERVICE }}
          registry_host: ${{ env.REGISTRY_HOST }}
          registry_endpoint: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          image_tag: ${{ github.sha }}
          registry_username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
