name: API Test

on:
  pull_request:
    branches:
      - develop
    paths:
      - backend/uks/**

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
          
      - name: Wait for Redis to start
        run: sleep 15s

      - name: Print Redis Container Logs
        run: docker logs redis

      - name: Test
        run: |
          cd backend/uks && mvn clean test
