name: Angular App Push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/uks/**

env:
  SERVICE: front
  REGISTRY_HOST: docker.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd frontend/uks && npm install

      - name: Run Tests
        run: |
          cd frontend/uks && npm test

      - uses: ./.github/workflows/composite/build-push
        if: success()
        with:
          service: ${{ env.SERVICE }}
          registry_host: ${{ env.REGISTRY_HOST }}
          registry_endpoint: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          image_tag: ${{ github.sha }}
          registry_username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
