name: Angular App PR Test

on:
  pull_request:
    branches:
      - develop
    paths:
      - frontend/uks/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd frontend/uks && npm install

      - name: Run Tests
        run: |
          cd frontend/uks && npm test
