name: Angular App Push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/uks/**
  pull_request:
    branches:
      - develop

env:
  SERVICE: front
  IMAGE: angular-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd frontend/uks && npm install

      - name: Run Tests
        run: |
          cd frontend/uks && npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME  }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD  }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository

      - name: Build and push Docker image with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build front
          docker-compose -f docker-compose.yml push front
